export const actions = {
  ADD_PEOPLE: 'ADD_PEOPLE',
  ADD_PLANETS: 'ADD_PLANETS',
  ADD_FILMS: 'ADD_FILMS',
  ADD_SPECIES: 'ADD_SPECIES',
  ADD_VEHICLES: 'ADD_VEHICLES',
  ADD_STARSHIPS: 'ADD_STARSHIPS',

}